/**
 * Request correlation id.
 *
 * Generated by src/proxy.ts for every request it handles, forwarded to the
 * application as a request header and echoed to the client as a response
 * header, so a user report ("error at 14:02, id 3f2a…") can be matched to the
 * log lines and the GlitchTip event of that request.
 *
 * Always generated here, never taken from the incoming request: a client
 * that could choose its own id could make its requests look like someone
 * else's in the logs.
 *
 * Kept free of any dependency so the proxy can import it without pulling the
 * logger in.
 */
export const REQUEST_ID_HEADER = "x-request-id";

export function generateRequestId(): string {
  return crypto.randomUUID();
}
